defaults:
  - _self_
  - wandb: private.yaml
  - override hydra/hydra_logging: disabled
  - override hydra/job_logging: disabled
tensorboard: 
  enabled: True
# disable hydra outputs
hydra:
  output_subdir: null
  run:
    dir: .

name: "lora-traffic-linear"
pretrained_feature_extractor: "/home/model-server/workspace/solo-learn/trained_models/pretrain-256/byol-traffic-rc-31-ep=581.ckpt"
backbone:
  name: "traffic_encoder_simple" # traffic_encoder_simple traffic_transformer
  kwargs:
    input_dim: 500
    d_model: 256 # hidden layer dimensions
    seq_length : 400
    n_head : 4
    kernel_size : 3
    n_layer : 6
    out_dim: 256

# pretrained_feature_extractor: "/home/model-server/code/solo-learn/trained_models/traffic_fft_cl/126/byol-traffic-126-ep=999.ckpt"
# backbone:
#   name: "traffic_encoder"
#   kwargs:
#     input_dim: 500
#     d_model: 500 # hidden layer dimensions
#     seq_length : 401 
#     n_head : 4
#     kernel_size : 3
#     n_layer : 5



# LoRA parameters
lora:
  r : 16
  alpha: 32
  dropout : 0.2


embeding:
  dim : 500
pretrain_method: "byol"
data:
  dataset: CICIoT2022 # change here for cifar100 ISCXTor2016 CrossPlatform-Android CICIoT2022
  train_path: "/home/model-server/workspace/solo-learn/dataset/CICIoT2022"
  val_path: "/home/model-server/workspace/solo-learn/dataset/CICIoT2022"
  format: "image_folder"
  num_workers: 4
  data_fraction: -1
optimizer:
  name: "sgd"
  batch_size: 256
  lr: 0.1
  weight_decay: 0
scheduler:
  name: "step"
  lr_decay_steps: [60, 80]
checkpoint:
  enabled: True
  dir: "trained_models"
  frequency: 1
auto_resume:
  enabled: False
finetune: False
adversarial: False
# overwrite PL stuff
max_epochs: 100
devices: [0]
sync_batchnorm: True
accelerator: "gpu"
strategy: "ddp"
precision: 16
