defaults:
  - _self_
  - augmentations: asymmetric.yaml
  - wandb: private.yaml
  - override hydra/hydra_logging: disabled
  - override hydra/job_logging: disabled

tensorboard: 
  enabled: True
# disable hydra outputs
hydra:
  output_subdir: null
  run:
    dir: .

name: "traffic-rc" # change here for cifar100
method: "traffic_fft_rc"
backbone:
  name: "traffic_encoder_simple" # traffic_encoder_simple traffic_transformer
  kwargs:
    input_dim: 500
    d_model: 256 # hidden layer dimensions
    seq_length : 400
    n_head : 4
    kernel_size : 3
    n_layer : 6
    out_dim: 256

method_kwargs:
  proj_hidden_dim: 4096
  proj_output_dim: 256
  pred_hidden_dim: 4096
embeding:
  dim : 500
momentum:
  base_tau: 0.99
  final_tau: 1.0
  classifier: False
data:
  dataset: ISCXVPN2016
  train_path: "/home/model-server/code/LiMTa/dataset/ISCXVPN2016/"
  val_path: "/home/model-server/code/LiMTa/dataset/ISCXVPN2016/"
  format: "image_folder"
  num_workers: 4
optimizer:
  name: "lars"
  batch_size: 128
  lr: 0.1875
  classifier_lr: 0.1
  weight_decay: 1e-5
  kwargs:
    clip_lr: True
    eta: 0.02
    exclude_bias_n_norm: True
scheduler:
  name: "warmup_cosine"
checkpoint:
  enabled: True
  dir: "trained_models"
  frequency: 1
auto_resume:
  enabled: False

# overwrite PL stuff
max_epochs: 500
devices: [0]
sync_batchnorm: True
accelerator: "gpu"
strategy: "ddp"
precision: 16
